// <auto-generated>
// Code generated by LUISGen vakonadjen_Dispatch.json -cs Luis.Dispatch -o C:\Users\darrenj\source\repos\ai\solutions\Virtual-Assistant\src\csharp\assistant\Dialogs\Shared\Resources
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public class Dispatch: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            l_Automotive, 
            l_Calendar, 
            l_Email, 
            l_General, 
            l_News, 
            l_PointOfInterest, 
            l_Restaurant, 
            l_ToDo, 
            None, 
            q_Chitchat, 
            q_FAQ
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] ADDRESS;
            public string[] KEYWORD;
            public string[] ShopContent;
            public string[] TaskContentPattern;

            // Pattern.any
            public string[] topic;

            // Instance
            public class _Instance
            {
                public InstanceData[] ADDRESS;
                public InstanceData[] KEYWORD;
                public InstanceData[] ShopContent;
                public InstanceData[] TaskContentPattern;
                public InstanceData[] topic;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<Dispatch>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
