//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneSkillTest.Flow.Utterances {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutgoingCallUtterances {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutgoingCallUtterances() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneSkillTest.Flow.Utterances.OutgoingCallUtterances", typeof(OutgoingCallUtterances).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call bob.
        /// </summary>
        internal static string OutgoingCallContactName {
            get {
                return ResourceManager.GetString("OutgoingCallContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make a call.
        /// </summary>
        internal static string OutgoingCallNoEntities {
            get {
                return ResourceManager.GetString("OutgoingCallNoEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call 0118 999 88199 9119 725 3.
        /// </summary>
        internal static string OutgoingCallPhoneNumber {
            get {
                return ResourceManager.GetString("OutgoingCallPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bob.
        /// </summary>
        internal static string RecipientContactName {
            get {
                return ResourceManager.GetString("RecipientContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0118 999 88199 9119 725 3.
        /// </summary>
        internal static string RecipientPhoneNumber {
            get {
                return ResourceManager.GetString("RecipientPhoneNumber", resourceCulture);
            }
        }
    }
}
